# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class CedanaOrch < Formula
  desc ""
  homepage "cedana.ai"
  version "0.6.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.6.2/cedana-orch_0.6.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9c412ab411fc15a47a564f4bcee4702a7446bfd690c9a4efd5a64b39cae8128a"

      def install
        bin.install "cedana-orch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.6.2/cedana-orch_0.6.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f9741843d60ad21f76033f3bf448a136b291ad9baf2b44ce653a284398262680"

      def install
        bin.install "cedana-orch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.6.2/cedana-orch_0.6.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bf2633d99b9d19865f21a60c826d926f16118478f24d39577087df4b3f1bf7a0"

      def install
        bin.install "cedana-orch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.6.2/cedana-orch_0.6.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9952cc4971f7a22738fc12ef141afc8b6447b6468483a0ce843468310913bea9"

      def install
        bin.install "cedana-orch"
      end
    end
  end
end
