# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class CedanaOrch < Formula
  desc ""
  homepage "cedana.ai"
  version "0.7.7"

  on_macos do
    url "https://github.com/cedana/cedana-orch/releases/download/v0.7.7/cedana-orch_0.7.7_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "86a35d8b5fb3b10e997f659f3bee22f630f0e21bf6ccca3b8fb991cffd88ab80"

    def install
      bin.install "cedana-orch"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the CedanaOrch
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.7.7/cedana-orch_0.7.7_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dec84bdf51a2d94cf2bacb7058b9b531447e9e105d58521703412c802da784f2"

      def install
        bin.install "cedana-orch"
      end
    end
  end
end
