# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class CedanaOrch < Formula
  desc ""
  homepage "cedana.ai"
  version "0.4.99"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.4.99/cedana-orch_0.4.99_darwin_amd64.tar.gz", using: PrivateRepoDownloadStrategy
      sha256 "c2136e0da0f33e1d4928a1dce69d7940573f55c569865dab625a1ff9108ad89c"

      def install
        bin.install "cedana-orch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.4.99/cedana-orch_0.4.99_darwin_arm64.tar.gz", using: PrivateRepoDownloadStrategy
      sha256 "fc9d884892daa6277724bc8b4ee9d1c277e3ae13ea4ed112c3b7ae56d56e9547"

      def install
        bin.install "cedana-orch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.4.99/cedana-orch_0.4.99_linux_arm64.tar.gz", using: PrivateRepoDownloadStrategy
      sha256 "215d849828f84c4cf0d7d7f97a8a7a8983fd10f360d2b1ebf7b2873f05fd92a4"

      def install
        bin.install "cedana-orch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cedana/cedana-orch/releases/download/v0.4.99/cedana-orch_0.4.99_linux_amd64.tar.gz", using: PrivateRepoDownloadStrategy
      sha256 "a8529bc2dee647bc33121a68531ad40289f282c4b89af692be95119f44c626e7"

      def install
        bin.install "cedana-orch"
      end
    end
  end
end
